try:
    result = 45/0
except:
    print('error happened')
finally:
    print('finally here')
print('finish')